name: lts
on:
  merge_group:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "45 2 * * *" # 2:45am-ish UTC everyday (approx 40 minutes after akmods images run)
  workflow_dispatch:

jobs:
  build-lts:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      ucore_stream: lts
      arch: "['aarch64','x86_64']"
